### ISSUE TITLE
Message fonctionality

### ISSUE THREAD

**Issue by carpuplay** [carpuplay/Snake#10]
We created an message function, but it seems not working properly, so we will make again this function.

**Comment by Oriol20051** [comment]
To create the functionality of the message we have to define a message with a color, typography and coordinates, then we had to call the message with its respective information mentioned above.
![image](https://user-images.githubusercontent.com/106106675/169904332-3e9d78af-2ccd-4402-ba28-b87a3960c89f.png)
![image](https://user-images.githubusercontent.com/106106675/169904406-1b17d46f-224b-4bb7-97ec-41c1a0c0de1a.png)
