### ISSUE TITLE
GameClose feature

### ISSUE THREAD

**Issue by carpuplay** [carpuplay/Snake#15]
We wanted to keep the game runing even if we losed, so we make an secondary loop that allows us to keep the script on. Meanwhile, we have to know how to make it run again

**Comment by Oriol20051** [comment]
The game close featured is a simple varible that allows the game to be opened although you lose. To do this we created a display black to hide the game but this doesn't work, so we created a message that it displays when you lose and give to option, close the game or contiunue, we had to assing key to make the action.
![image](https://user-images.githubusercontent.com/106106675/169973438-cf24dbe2-6cb7-4bab-88b0-1a4d9a4cd1f8.png)
![image](https://user-images.githubusercontent.com/106106675/169973514-149f2963-aed6-49ad-922a-2c07c6475d06.png)
![image](https://user-images.githubusercontent.com/106106675/169973587-163f683f-a113-4f06-bb8e-a853ddd16bb3.png)
