### ISSUE TITLE
Add a second Apple

### ISSUE THREAD

**Issue by carpuplay** [carpuplay/Snake#26]
We think that adding a secon apple can make the game funnier.

**Comment by Oriol20051** [comment]
To create a second apple we simply had to duplicate the code of the first apple.

**Comment by carpuplay** [comment]
![image](https://user-images.githubusercontent.com/105707690/169903027-445f46dd-66ab-4095-b819-5f4ccd8f5631.png)

There are the two apples spwan code, then this same code is repited one again when the apples are eaten.
