### ISSUE TITLE
Display an image when died

### ISSUE THREAD

**Issue by carpuplay** [carpuplay/Snake#27]
We want to display an image when died, we think that this could improve the quality of the game.

**Comment by carpuplay** [comment]
we made an function that displays the images, but python is not responding properly, it seems that images are not found.

**Comment by Oriol20051** [comment]
At the moment of death we wanted an image to appear, that was not very complicated we just had to use the pygame.image.load and add an image, we had to take into account that the image was in the same file as the program.
![image](https://user-images.githubusercontent.com/106106675/169908460-272908e6-569a-4d26-a77e-224f77a3fe8a.png)
