### ISSUE TITLE
Snake is growing up only 2px after fps fix

### ISSUE THREAD

**Issue by carpuplay** [carpuplay/Snake#32]
After we added the #29 fix, our snake started eating the apples more apart the center of themeselves, so when the food converted to snake body, there wern't aligned at 1 full section.

**Comment by Oriol20051** [comment]
To fix this problem we changed the Lenght_of_snake+=1 for Lenght_of_snake+=8 because the snake was only growing 2 pixels per apple so adding 8 pixels the snake will grow 10 pixels.
![image](https://user-images.githubusercontent.com/106106675/169972026-409fd20b-6a5f-4d51-8a0b-15452b403c84.png)
